### ISSUE TITLE
3D UI Crashed when placing Arrow Gruts

### ISSUE THREAD

**Issue by Cosmack** [lyrgard/HexScape#100]
Just the 3d view crashed. Was able to save my game, restart program and load game back up no problem.

Output from console:

Aug 06, 2015 10:30:09 PM com.jme3.scene.plugins.MTLLoader loadTexture
WARNING: Cannot locate asset/heroscape/3dObjects/ArrowGruts2/C:\Users\KRNW5701\Downloads\Wave1Assets\heroscape\3dObjects\ArrowGruts3\ArrowGruts3.png (Flipped) (Mipmapped) for material asset/heroscape/3dObjects/ArrowGruts2/ArrowGruts2.mtl
Aug 06, 2015 10:30:09 PM com.jme3.app.Application handleError
SEVERE: Uncaught exception thrown in Thread[LWJGL Renderer Thread,6,main]
java.lang.ClassCastException: com.jme3.asset.AssetKey cannot be cast to com.jme3.asset.TextureKey
	at com.jme3.texture.Texture.setKey(Texture.java:409)
	at com.jme3.scene.plugins.MTLLoader.loadTexture(MTLLoader.java:187)
	at com.jme3.scene.plugins.MTLLoader.readLine(MTLLoader.java:233)
	at com.jme3.scene.plugins.MTLLoader.load(MTLLoader.java:305)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:288)
	at com.jme3.scene.plugins.OBJLoader.loadMtlLib(OBJLoader.java:336)
	at com.jme3.scene.plugins.OBJLoader.readLine(OBJLoader.java:389)
	at com.jme3.scene.plugins.OBJLoader.load(OBJLoader.java:578)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:288)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:374)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:378)
	at fr.lyrgard.hexScape.model.model3d.loader.ObjModelLoader.load(ObjModelLoader.java:29)
	at fr.lyrgard.hexScape.service.ExternalModelService.getModel(ExternalModelService.java:44)
	at fr.lyrgard.hexScape.service.PieceManager.getSpatial(PieceManager.java:42)
	at fr.lyrgard.hexScape.control.PlacePieceByMouseAppState.setPieceToPlace(PlacePieceByMouseAppState.java:58)
	at fr.lyrgard.hexScape.control.PieceControlerAppState.changeStateTo(PieceControlerAppState.java:267)
	at fr.lyrgard.hexScape.control.PieceControlerAppState.onAction(PieceControlerAppState.java:128)
	at com.jme3.input.InputManager.invokeActions(InputManager.java:169)
	at com.jme3.input.InputManager.onMouseButtonEventQueued(InputManager.java:433)
	at com.jme3.input.InputManager.processQueue(InputManager.java:833)
	at com.jme3.input.InputManager.update(InputManager.java:883)
	at com.jme3.app.Application.update(Application.java:604)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:231)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglCanvas.runLoop(LwjglCanvas.java:229)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:228)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lyrgard** [comment]
Good catch !
There was an erroneous path in the data of the ArrowGrut2.

Can you try to download again the data for the Wave 1 here https://drive.google.com/open?id=0Bxgp7Kno-mOIVlcyakNaT2F5Nlk
Import it (it will overwrite any previous Wave1 data) and try it again ? I corrected the data.

**Comment by Cosmack** [comment]
New Wave 1 works perfectly.
